site_name: ipard
site_author: 4Tel

repo_name: 4Tel/Doc_ipard
repo_url: https://github.com/4Tel/Doc_ipard

theme:
  name: material
  language: ko
  # override path
  custom_dir: overrides
  # logo: 
  # favicon: 
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate  
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  
  features:
    # Navigation settings
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    # search settings
    - search.suggest
    - search.highlight
    # Code Block
    - content.code.annotate
    - content.code.copy
    # etc.
    - content.footnote.tooltips
    - content.tooltips
    - toc.follow

markdown_extensions:
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # annotation
  - attr_list
  - md_in_html
  # codeblock
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # tabs
  - pymdownx.tabbed:
      alternate_style: true
  # table
  - tables
  # diagram
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # footnotes
  - footnotes
  # formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # images
  - pymdownx.blocks.caption
  # lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # KaTeX
  - pymdownx.arithmatex:
      generic: true
  # tooltip
  - abbr
  - pymdownx.snippets


extra_javascript:
  # KaTeX
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  # KaTeX
  - https://unpkg.com/katex@0/dist/katex.min.css


extra:
  # Comments Setting.
  # See overrides/main.html for more details
  comments:
    enable: true
    mode: giscus
    title: "💬 댓글"
    repo: 4Tel/Doc_ipard
    repo_id: R_kgDOPHwk7g
    category: General
    category_id: DIC_kwDOPHwk7s4CsjCr
    mapping: pathname
    strict: 1
    reactions_enabled: 1
    emit_metadata: 0
    input_position: top
    theme: preferred_color_scheme
    lang: ko
    crossorigin: anonymous
#   analysis:
#     provider: google
#     property: 'G-XXXXXXXXXX'
  
# plugins
plugins:
  - search:
      lang: ko
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
  - git-revision-date-localized:
      type: iso_datetime
  - awesome-pages
