import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { SidebarItemAutogenerated } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

function auto(dirName: string): SidebarItemAutogenerated {
  return { type: 'autogenerated', dirName: dirName }
};

const homeBars: SidebarsConfig = {
  homeBar: [
    {
      type: 'doc',
      id: 'index',
    },
  ],
}

const aboutBars: SidebarsConfig = {
  aboutBar: [auto('01.about')],
}

const theoryBars: SidebarsConfig = {
  theoryBar: [auto('01.theory')],
}

const usageBars: SidebarsConfig = {
  usageBar: [auto('01.usage')],
}

const devBars: SidebarsConfig = {
  devBar: [auto('01.dev')],
}

const ruleBars: SidebarsConfig = {
  ruleBar: [auto('01.rule')],
}


const sidebars: SidebarsConfig = {
  ...homeBars,
  ...aboutBars,
  ...theoryBars,
  ...usageBars,
  ...devBars,
  ...ruleBars,
}

export default sidebars